const keywords = { 
  "add-card": ["card", "add"],
  "add-submenu": [],
  "add-template": [],
  "align-center": [],
  "align-justify": [],
  "align-left": [],
  "align-none": [],
  "align-right": [],
  "archive": ["folder", "directory"],
  "arrow-down": [],
  "arrow-left": [],
  "arrow-right": [],
  "arrow-up": [],
  "aspect-ratio": [],
  "at-symbol": ["@", "email"],
  "audio": ["song", "music"],
  "backup": ["save", "restore"],
  "block-default": [],
  "block-meta": ["chart"],
  "block-table": ["grid", "layout"],
  "border": [],
  "box": [],
  "brush": ["paint", "draw", "stroke", "paintbrush", "painting", "writing"],
  "bug": ["error", "issue"],
  "button": [],
  "buttons": [],
  "calendar": ["day", "date", "days", "dates"],
  "cancel-circle-filled": [],
  "caption": [],
  "capture-photo": ["camera"],
  "capture-video": ["camera"],
  "category": ["grid"],
  "chart-bar": [],
  "check": ["tick", "done", "success", "ok"],
  "chevron-down-small": ["arrow"],
  "chevron-down": ["arrow"],
  "chevron-left-small": ["arrow"],
  "chevron-left": ["arrow"],
  "chevron-right-small": ["arrow"],
  "chevron-right": ["arrow"],
  "chevron-up-down": ["arrow"],
  "chevron-up": ["arrow"],
  "classic": ["keyboard"],
  "close-small": ["x"],
  "close": ["x"],
  "cloud-upload": [],
  "cloud": [],
  "code": ["tag"],
  "cog": ["gear", "settings"],
  "color": ["drop"],
  "column": [],
  "columns": [],
  "comment-author-avatar": ["user"],
  "comment-author-name": [],
  "comment-content": [],
  "comment-edit-link": ["writing"],
  "comment-reply-link": [],
  "comment": ["bubble", "chat", "talk", "speak"],
  "connection": [],
  "copy-small": [],
  "copy": [],
  "cover": ["bookmark"],
  "create": ["add", "plus"],
  "crop": [],
  "currency-dollar": ["money", "cash"],
  "currency-euro": ["money", "cash"],
  "currency-pound": ["money", "cash"],
  "custom-link": [],
  "custom-post-type": [],
  "desktop": ["computer", "laptop"],
  "details": [],
  "download": ["arrow", "import"],
  "drafts": [],
  "drag-handle": [],
  "drawer-left": ["sidebar"],
  "drawer-right": ["sidebar"],
  "edit": [],
  "external": ["link"],
  "file": ["archive", "folder", "document", "directory"],
  "filter": [],
  "flip-horizontal": [],
  "flip-vertical": [],
  "footer": [],
  "format-bold": [],
  "format-capitalize": [],
  "format-indent-rtl": [],
  "format-indent": [],
  "format-italic": [],
  "format-list-bullets-rtl": [],
  "format-list-bullets": [],
  "format-list-numbered-rtl": [],
  "format-list-numbered": [],
  "format-lowercase": [],
  "format-ltr": [],
  "format-outdent-rtl": [],
  "format-outdent": [],
  "format-rtl": [],
  "format-strikethrough": [],
  "format-underline": [],
  "format-uppercase": [],
  "fullscreen": [],
  "funnel": ["filter"],
  "gallery": ["image", "images"],
  "globe": ["world", "earth", "global"],
  "grid": ["table", "array"],
  "group": [],
  "handle": [],
  "header": [],
  "heading-level-1": ["h1"],
  "heading-level-2": ["h2"],
  "heading-level-3": ["h3"],
  "heading-level-4": ["h4"],
  "heading-level-5": ["h5"],
  "heading-level-6": ["h6"],
  "heading": ["save", "bookmark"],
  "help-filled": [],
  "help": [],
  "home": ["house", "dashboard"],
  "html": [],
  "image": ["picture", "photo"],
  "inbox": [],
  "info": ["help"],
  "insert-after": [],
  "insert-before": [],
  "institution": ["bank", "building"],
  "justify-center": [],
  "justify-left": [],
  "justify-right": [],
  "justify-space-between": [],
  "justify-stretch": [],
  "key": [],
  "keyboard-close": [],
  "keyboard-return": ["arrow"],
  "keyboard": [],
  "language": ["translate"],
  "layout": [],
  "level-up": [],
  "lifesaver": [],
  "line-dashed": [],
  "line-dotted": [],
  "line-solid": [],
  "link-off": [],
  "link": [],
  "list-item": [],
  "list-view": [],
  "list": [],
  "lock-outline": [],
  "lock-small": [],
  "lock": [],
  "login": [],
  "loop": [],
  "map-marker": [],
  "media-and-text": [],
  "media": [],
  "megaphone": [],
  "menu": [],
  "mobile": [],
  "more-horizontal-mobile": ["ellipsis", "extra"],
  "more-horizontal": ["ellipsis", "extra"],
  "more-vertical": ["ellipsis", "extra"],
  "more": [],
  "move-to": ["arrow"],
  "navigation": [],
  "next": [],
  "not-found": [],
  "offline": [],
  "overlay-text": [],
  "page-break": [],
  "page": [],
  "pages": [],
  "paragraph": [],
  "payment": [],
  "pencil": ["writing"],
  "people": ["users"],
  "percent": [],
  "pin-small": [],
  "pin": [],
  "plugins": [],
  "plus-circle-filled": [],
  "plus-circle": [],
  "plus": [],
  "position-center": [],
  "position-left": [],
  "position-right": [],
  "post-author": [],
  "post-categories": [],
  "post-comments-count": [],
  "post-comments-form": [],
  "post-comments": [],
  "post-content": [],
  "post-date": ["calendar", "day"],
  "post-excerpt": [],
  "post-featured-image": [],
  "post-list": [],
  "post-terms": [],
  "post": [],
  "preformatted": [],
  "previous": [],
  "pull-left": [],
  "pull-right": [],
  "pullquote": [],
  "query-pagination-next": [],
  "query-pagination-numbers": [],
  "query-pagination-previous": [],
  "query-pagination": [],
  "quote": [],
  "receipt": [],
  "redo": [],
  "remove-bug": ["delete", "error", "issue"],
  "remove-submenu": [],
  "replace": [],
  "reset": [],
  "resize-corner-n-e": [],
  "reusable-block": ["reload", "restore", "rotate", "refresh"],
  "rotate-left": ["arrow"],
  "rotate-right": ["arrow"],
  "row": [],
  "rss": ["feed"],
  "search": [],
  "seen": [],
  "separator": [],
  "settings": [],
  "shadow": [],
  "share": [],
  "shield": [],
  "shipping": [],
  "shortcode": [],
  "shuffle": [],
  "sidebar": [],
  "sides-all": [],
  "sides-axial": [],
  "sides-bottom": [],
  "sides-horizontal": [],
  "sides-left": [],
  "sides-right": [],
  "sides-top": [],
  "sides-vertical": [],
  "site-logo": [],
  "stack": [],
  "star-empty": [],
  "star-filled": [],
  "star-half": [],
  "store": [],
  "stretch-full-width": [],
  "stretch-wide": [],
  "styles": [],
  "subscript": [],
  "superscript": [],
  "swatch": [],
  "symbol-filled": [],
  "symbol": [],
  "table-column-after": [],
  "table-column-before": [],
  "table-column-delete": [],
  "table-of-contents": [],
  "table-row-after": [],
  "table-row-before": [],
  "table-row-delete": [],
  "table": [],
  "tablet": [],
  "tag": [],
  "term-description": [],
  "text-color": [],
  "text-horizontal": [],
  "text-vertical": [],
  "tip": [],
  "title": [],
  "tool": [],
  "trash": [],
  "trending-down": [],
  "trending-up": [],
  "typography": [],
  "undo": [],
  "ungroup": [],
  "unlock": [],
  "unseen": [],
  "update": [],
  "upload": [],
  "verse": [],
  "video": [],
  "warning": [],
  "widget": [],
  "wordpress": ["wp", "logo"]
};

module.exports = { keywords };
